Fork
- Install from sources rather than from clone
- Use Hellowlol fork
- Simplify the scripts and use YunoHost best practices
- Remove non-local install (use the redirect_ynh app for that)

diff --git a/scripts/backup b/scripts/backup
--- a/scripts/backup
+++ b/scripts/backup
@@ -1,37 +1,27 @@
 #!/bin/bash
 
-# Common variable declaration
-app_id=htpc-manager
-app_user=htpc-manager
-app_install_dir="/opt/yunohost/${app_id}"
-app_data_dir="/home/yunohost.app/${app_id}"
+# causes the shell to exit if any subcommand or pipeline returns a non-zero status
+set -e
 
-# Retrieve arguments
-app_method="$(sudo yunohost app setting ${app_id} method)"
-app_domain="$(sudo yunohost app setting ${app_id} domain)"
+app=htpc-manager
 
 # The parameter $1 is the backup directory location
-# which will be compressed afterward
-app_backup_dir="$1/apps/${app_id}"
-sudo mkdir -p $app_backup_dir
+	backup_dir="$1/apps/$app"
+	sudo mkdir -p $backup_dir
 
-
-# Backup files if localhost installation
-if [[ $app_method == "LOCAL"* ]]; then
-
+# Backup files
 	# Backup sources
-	sudo cp -a $app_install_dir/. $app_backup_dir/sources
+	sudo cp -a /opt/yunohost/$app/. $backup_dir/sources
 
 	# Backup data
-	sudo cp -a $app_data_dir/. $app_backup_dir/data
+	sudo cp -a /home/yunohost.app/$app/. $backup_dir/data
 	
 	# Backup daemon config
-	sudo cp -a /etc/default/$app_id $app_backup_dir/conf/$app_id.default
-	sudo cp -a /etc/init.d/$app_id $app_backup_dir/conf/$app_id.init
-	
-fi
+	sudo cp -a /etc/default/$app $backup_dir/conf/$app.default
+	sudo cp -a /etc/init.d/$app $backup_dir/conf/$app.init
 
 
 # Copy Nginx and YunoHost parameters to make the script "standalone"
-sudo cp -a /etc/yunohost/apps/$app_id/. $app_backup_dir/yunohost
-sudo cp -a /etc/nginx/conf.d/$app_domain.d/$app_id.conf $app_backup_dir/nginx.conf
+	sudo cp -a /etc/yunohost/apps/$app/. $backup_dir/yunohost
+	domain=$(sudo yunohost app setting $app domain)
+	sudo cp -a /etc/nginx/conf.d/$domain.d/$app.conf $backup_dir/nginx.conf
diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,146 +1,79 @@
 #!/bin/bash
 
-#debug commands
-#exec > >(tee /tmp/debug-install.log)
-#exec 2>&1
+# causes the shell to exit if any subcommand or pipeline returns a non-zero status
+set -e
+
+app=htpc-manager
 
 # Retrieve arguments
-app_domain=$1
-app_path=$2
-app_public=$3
-app_method=$4
-app_port=$5
-app_fork=$6
-app_opts=$7
-app_host=$8
-
-# Basic variable declaration
-BASEDIR="$(dirname "$(pwd)")"
-
-# Common variable declaration
-app_id=htpc-manager
-app_user=htpc-manager
-app_local_host="127.0.0.1"
-app_python_bin="/usr/bin/python"
-## Destinations definitions
-app_install_dir="/opt/yunohost/${app_id}"
-app_data_dir="/home/yunohost.app/${app_id}"
-app_logs_dir="/var/log/${app_id}"
-app_pid_file="/var/run/${app_id}/${app_id}.pid"
-## Sources definitions
-app_src_dfts="$BASEDIR/conf/${app_id}.defaults"
-app_src_init="$BASEDIR/conf/${app_id}.init"
-app_src_nginx_conf="$BASEDIR/conf/nginx.conf"
-
+	domain=$1
+	path=$2
 
 # Check domain/path availability
-sudo yunohost app checkurl $app_domain$app_path -a $app_id
-if [[ ! $? -eq 0 ]]; then
-	exit 1
-fi
+	sudo yunohost app checkurl $domain$path -a $app \
+		|| (echo "Path not available: $domain$path" && exit 1)
 
+# Find an unused port
+	port=8089
+	sudo yunohost app checkport $port
+	while [[ ! $? -eq 0 ]]
+	do
+		port=$(($port + 1))
+		sudo yunohost app checkport $port
+	done
+	sudo yunohost app setting $app port -v "$port"
 
-# Make install if localhost installation
-if [[ $app_method == "LOCAL"* ]]; then
+# Install dependencies
+	sudo apt-get install -y -qq build-essential git python-imaging python-dev python-setuptools python-pip python-cherrypy vnstat
+	sudo pip install psutil
 
-	# Check port availability
-	sudo yunohost app checkport $app_port
-	if [[ ! $? -eq 0 ]]; then
-		exit 1
-	fi
-	
-	# Make directories
-	sudo mkdir -p $app_data_dir
-	sudo mkdir -p $app_install_dir
-	
-	# Install latest version of app using the fork
-	sudo apt-get install -y git-core
-	sudo git clone $app_fork $app_install_dir
-	
-	# Install dependencies (using virtualenv)
-	if [[ $(python --version 2>&1) != Python\ 2* ]]; then
-		app_python_bin="${app_install_dir}/bin/python"
-		sudo apt-get install -y python-pip python-virtualenv python-dev uwsgi uwsgi-plugin-python
-		sudo virtualenv $app_install_dir
-		sudo bash -c "source $app_install_dir/bin/activate && pip install cheetah"
-	fi
-	
-	# Install urllib3 patch for Python 2.7.9
-	if [[ $(python --version 2>&1) == "Python 2.7.9" ]]; then
-		patch_dir="libs/requests/packages/urllib3/contrib"
-		sudo cp -a $BASEDIR/sources/$patch_dir/. $app_install_dir/$patch_dir
-	fi
-	
-	# Install dependencies if XBMC used
-	if [[ $app_opts == "Yes" ]]; then
-		sudo apt-get install -y libjpeg libjpeg-dev libpng-dev libfreetype6 libfreetype6-dev zlib1g-dev
-		sudo apt-get install -y python-pip
-		sudo bash -c "pip install PIL"
-	fi
-	
-	# Create app user
-	id -u $app_user &>/dev/null || sudo useradd --home-dir $app_data_dir --shell /bin/false $app_user
-	
-	# Configure daemon
-	sudo sed -i "s@USERTOCHANGE@$app_user@g" $app_src_dfts
-	sudo sed -i "s@APPDIRTOCHANGE@$app_install_dir@g" $app_src_dfts
-	sudo sed -i "s@DATADIRTOCHANGE@$app_data_dir@g" $app_src_dfts
-	sudo sed -i "s@PIDFILETOCHANGE@$app_pid_file@g" $app_src_dfts
-	sudo sed -i "s@PYTBINTOCHANGE@$app_python_bin@g" $app_src_dfts
-	sudo sed -i "s@PATHTOCHANGE@$app_path@g" $app_src_dfts
-	sudo sed -i "s@PORTTOCHANGE@$app_port@g" $app_src_dfts
-	sudo cp -a $app_src_dfts /etc/default/$app_id
-	sudo cp -a $app_src_init /etc/init.d/$app_id
-	
-	# Redirect log file
-	if [[ $app_logs_dir != "$app_data_dir"* ]]; then
-		sudo mkdir -p $app_logs_dir
-		sudo chown -R $app_user $app_logs_dir
-		sudo chmod +x -R $app_logs_dir
-		sudo sed -i "s@self.logfile =.*@self.logfile = '$app_logs_dir/$app_id.log'@g" $app_install_dir/htpc/log.py
-	fi
-	
-	# Set rights
-	sudo chown -R $app_user $app_install_dir
-	sudo chown -R $app_user $app_data_dir
-	sudo chmod +x /etc/init.d/$app_id
-	sudo chmod +x -R $app_install_dir
-	sudo chmod +x -R $app_data_dir
-	
-	# Add service to YunoHost's monitoring
-	sudo yunohost service add $app_id --log $app_logs_dir --status "ps aux | grep $app_id | grep -v grep"
-	
-	# Start daemon at boot
-	sudo update-rc.d $app_id defaults
-	
-	# Start service
-	sudo service $app_id start
-	
-	# Set proxy host variable
-	app_host="http://${app_local_host}:${app_port}${app_path%/}"
-	
-fi
+# Copy source files
+	data_path=/home/yunohost.app/$app
+	final_path=/opt/yunohost/$app
+	sudo mkdir -p $data_path
+	sudo mkdir -p $final_path
+	sudo cp -a ../sources/. $final_path
 
+# Create app user and set permissions
+	id -u $app &>/dev/null || sudo useradd --home-dir $data_path --shell /bin/false $app
+	
+# Configure daemon
+	sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/htpc-manager.defaults
+	sudo sed -i "s@PORTTOCHANGE@$port@g" ../conf/htpc-manager.defaults
+	sudo cp -a ../conf/htpc-manager.defaults /etc/default/$app
+	sudo cp -a ../conf/htpc-manager.init /etc/init.d/$app
+	
+# Redirect log file
+	log_path=/var/log/$app
+	sudo mkdir -p $log_path
+	sudo chown -R $app $log_path
+	sudo chmod +x -R $log_path
+	sudo sed -i "s@self.logfile =.*@self.logfile = '$log_path/$app.log'@g" $final_path/htpc/log.py
+	
+# Set rights
+	sudo chown -R $app $final_path
+	sudo chown -R $app $data_path
+	sudo chmod +x /etc/init.d/$app
+	sudo chmod +x -R $final_path
+	sudo chmod +x -R $data_path
+	
+# Add service to YunoHost's monitoring
+	sudo yunohost service add $app --log $log_path --status "ps aux | grep $app | grep -v grep"
+	
+# Start daemon at boot
+	sudo update-rc.d $app defaults
+	
+# Start service
+	sudo service $app start
 
 # Remove trailing "/" for next commands
-app_path=${app_path%/}
+	path=${app_path%/}
 
-# Configure Nginx 
-sudo sed -i "s@PATHTOCHANGE@$app_path@g" $app_src_nginx_conf
-sudo sed -i "s@HOSTTOCHANGE@$app_host@g" $app_src_nginx_conf
-sudo cp $app_src_nginx_conf /etc/nginx/conf.d/$app_domain.d/$app_id.conf
-
-# If app is public, add url to SSOWat conf as skipped_uris
-if [[ $app_public == "Yes" ]]; then
-	# unprotected_uris allows SSO credentials to be passed anyway.
-	sudo yunohost app setting $app_id unprotected_uris -v "/"
-fi
-	
-# Save app settings
-sudo yunohost app setting $app_id public -v "$app_public"
-sudo yunohost app setting $app_id method -v "$app_method"
-sudo yunohost app setting $app_id host -v "$app_host"
+# Nginx
+	sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
+	sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
+	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
 
 # Reload Nginx and regenerate SSOwat conf
-sudo service nginx reload
-sudo yunohost app ssowatconf
+	sudo service nginx reload
+	sudo yunohost app ssowatconf
diff --git a/scripts/restore b/scripts/restore
--- a/scripts/restore
+++ b/scripts/restore
@@ -1,56 +1,46 @@
 #!/bin/bash
 
-# Common variable declaration
-app_id=htpc-manager
-app_user=htpc-manager
-app_install_dir="/opt/yunohost/${app_id}"
-app_data_dir="/home/yunohost.app/${app_id}"
+# causes the shell to exit if any subcommand or pipeline returns a non-zero status
+set -e
 
-# Retrieve arguments
-app_method="$(sudo yunohost app setting ${app_id} method)"
-app_domain="$(sudo yunohost app setting ${app_id} domain)"
+app=htpc-manager
 
 # The parameter $1 is the uncompressed restore directory location
-app_backup_dir="$1/apps/${app_id}"
+	backup_dir=$1/apps/$app
 
-
-# Restore files if localhost installation
-if [[ $app_method == "LOCAL"* ]]; then
-
+# Restore files
 	# Kill app
-	sudo service $app_id stop
-	sudo killall $app_id
+	sudo service $app stop
+	sudo killall $app
 
 	# Restore sources
-	sudo cp -a $app_backup_dir/sources/. $app_install_dir
+	sudo cp -a $backup_dir/sources/. /opt/yunohost/$app
 
 	# Restore data
-	sudo cp -a $app_backup_dir/data/. $app_data_dir
+	sudo cp -a $backup_dir/data/. /home/yunohost.app/$app
 	
 	# Restore daemon config
-	sudo cp -a $app_backup_dir/conf/$app_id.default /etc/default/$app_id 
-	sudo cp -a $app_backup_dir/conf/$app_id.init /etc/init.d/$app_id
+	sudo cp -a $backup_dir/conf/$app.default /etc/default/$app
+	sudo cp -a $backup_dir/conf/$app.init /etc/init.d/$app
 	
 	# Set rights
-	sudo chown -R $app_user $app_install_dir
-	sudo chown -R $app_user $app_data_dir
-	sudo chmod +x /etc/init.d/$app_id
-	sudo chmod +x -R $app_install_dir
-	sudo chmod +x -R $app_data_dir
+	sudo chown -R $app /opt/yunohost/$app
+	sudo chown -R $app /home/yunohost.app/$app
+	sudo chmod +x /etc/init.d/$app
+	sudo chmod +x -R /opt/yunohost/$app
+	sudo chmod +x -R /home/yunohost.app/$app
 	
 	# Start daemon at boot
-	sudo update-rc.d $app_id defaults
+	sudo update-rc.d $app defaults
 	
 	# Reload daemon
-	sudo service $app_id restart
-	
-fi
-
+	sudo service $app restart
 
 # Restore Nginx and YunoHost parameters
-sudo cp -a $app_backup_dir/yunohost/. /etc/yunohost/apps/$app_id
-sudo cp -a $app_backup_dir/nginx.conf /etc/nginx/conf.d/$app_domain.d/$app_id.conf
+	sudo cp -a $backup_dir/yunohost/. /etc/yunohost/apps/$app
+	domain=$(sudo yunohost app setting $app domain)
+	sudo cp -a $backup_dir/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
 
 # Reload Nginx and regenerate SSOwat conf
-sudo service nginx reload
-sudo yunohost app ssowatconf
+	sudo service nginx reload
+	sudo yunohost app ssowatconf
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,75 +1,57 @@
 #!/bin/bash
 
-# Basic variable declaration
-BASEDIR="$(dirname "$(pwd)")"
+# causes the shell to exit if any subcommand or pipeline returns a non-zero status
+set -e
 
-# Common variable declaration
-app_id=htpc-manager
-app_user=htpc-manager
-app_install_dir="/opt/yunohost/${app_id}"
-app_data_dir="/home/yunohost.app/${app_id}"
-app_logs_dir="/var/log/${app_id}"
-## Sources definitions
-app_src_init="$BASEDIR/conf/${app_id}.init"
-app_src_nginx_conf="$BASEDIR/conf/nginx.conf"
+app=htpc-manager
 
 # Retrieve arguments
-app_public="$(sudo yunohost app setting ${app_id} public)"
-app_method="$(sudo yunohost app setting ${app_id} method)"
-app_domain="$(sudo yunohost app setting ${app_id} domain)"
-app_path="$(sudo yunohost app setting ${app_id} path)"
-app_host="$(sudo yunohost app setting ${app_id} host)"
-
-
-# Make upgrade if localhost installation
-if [[ $app_method == "LOCAL"* ]]; then
-
-	# Kill app
-	sudo service $app_id stop
-	sudo killall $app_id
-	
-	# Upgrade to the latest version of app using the fork
-	cd $app_install_dir && sudo git pull
-	cd -
-
-	# Upgrade dependencies
-	
-	# Redirect log file
-	if [[ $app_logs_dir != $app_data_dir ]]; then
-		sudo sed -i "s@self.logfile =.*@self.logfile = '$app_logs_dir/$app_id.log'@g" $app_install_dir/htpc/log.py
-	fi
-	
-	# Update init file
-	sudo cp -a $app_src_init /etc/init.d/$app_id
-	
-	# Set rights
-	sudo chown -R $app_user $app_install_dir
-	sudo chmod +x /etc/init.d/$app_id
-	sudo chmod +x -R $app_install_dir
-	
-	# Start service
-	sudo service $app_id start
-	
-fi
-
+	domain=$(sudo yunohost app setting $app domain)
+	path=$(sudo yunohost app setting $app path)
+	port=$(sudo yunohost app setting $app port)
 
 # Remove trailing "/" for next commands
-app_path=${app_path%/}
+	path=${path%/}
+	
+# Kill app
+	sudo service $app stop
+	sudo killall $app
 
-# Configure Nginx 
-sudo sed -i "s@PATHTOCHANGE@$app_path@g" $app_src_nginx_conf
-sudo sed -i "s@HOSTTOCHANGE@$app_host@g" $app_src_nginx_conf
-sudo cp $app_src_nginx_conf /etc/nginx/conf.d/$app_domain.d/$app_id.conf
+# Copy source files
+	data_path=/home/yunohost.app/$app
+	final_path=/opt/yunohost/$app
+	sudo mkdir -p $data_path
+	sudo mkdir -p $final_path
+	sudo cp -a ../sources/. $final_path
 
-# If app is public, add url to SSOWat conf as skipped_uris
-if [[ $app_public = "Yes" ]];
-then
-	# See install script
-	sudo yunohost app setting $app_id unprotected_uris -v "/"
-	# Remove old settings
-	sudo yunohost app setting $app_id skipped_uris -d
-fi
+# Update daemon
+	sudo cp -a ../conf/htpc-manager.init /etc/init.d/$app
+	
+# Redirect log file
+	log_path=/var/log/$app
+	sudo mkdir -p $log_path
+	sudo chown -R $app $log_path
+	sudo chmod +x -R $log_path
+	sudo sed -i "s@self.logfile =.*@self.logfile = '$log_path/$app.log'@g" $final_path/htpc/log.py
+	
+# Set rights
+	sudo chown -R $app $final_path
+	sudo chown -R $app $data_path
+	sudo chmod +x /etc/init.d/$app
+	sudo chmod +x -R $final_path
+	sudo chmod +x -R $data_path
+	
+# Start service
+	sudo service $app start
+
+# Remove trailing "/" for next commands
+	path=${app_path%/}
+
+# Nginx
+	sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
+	sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
+	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
 
 # Reload Nginx and regenerate SSOwat conf
-sudo service nginx reload
-sudo yunohost app ssowatconf
+	sudo service nginx reload
+	sudo yunohost app ssowatconf
